ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check
    CHECK(status IN ('CONFIRMED','REJECTED','CANCELLED','BACKORDERED'));

CREATE TABLE IF NOT EXISTS tiangge_state (
    id bigint PRIMARY KEY,
    cursor bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS tiangge_processed_events (
    event_id varchar(100) PRIMARY KEY,
    seq bigint NOT NULL,
    processed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tiangge_pending_stock (
    seller_sku varchar(40) PRIMARY KEY,
    available integer NOT NULL CHECK(available >= 0)
);

CREATE TABLE IF NOT EXISTS tiangge_order_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiangge_order_id varchar(100) NOT NULL UNIQUE,
    shop_order_id bigint NOT NULL REFERENCES orders(order_id),
    decision varchar(30) NOT NULL,
    restocked boolean NOT NULL DEFAULT false
);

INSERT INTO tiangge_state(id, cursor)
VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;
