-- Extending the Modular Monolith - run in Supabase SQL Editor
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
CREATE TABLE inventory (product_id varchar(20) PRIMARY KEY,name varchar(100) NOT NULL,stock integer NOT NULL CHECK(stock>=0));
CREATE TABLE orders (order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,status varchar(20) NOT NULL CHECK(status IN ('CONFIRMED','REJECTED','CANCELLED')),reason varchar(255),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items (order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id bigint NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,product_id varchar(20) NOT NULL,quantity integer NOT NULL CHECK(quantity>0));
CREATE TABLE notifications (notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,message varchar(255) NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO inventory(product_id,name,stock) VALUES ('P100','Wireless Mouse',25),('P200','Mechanical Keyboard',10),('P300','USB-C Hub',0);
