-- Extending the Modular Monolith - run in Supabase SQL Editor
DROP TABLE IF EXISTS tiangge_order_links CASCADE;
DROP TABLE IF EXISTS tiangge_processed_events CASCADE;
DROP TABLE IF EXISTS tiangge_state CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;

CREATE TABLE inventory (product_id varchar(20) PRIMARY KEY,name varchar(100) NOT NULL,stock integer NOT NULL CHECK(stock>=0));
CREATE TABLE orders (order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,status varchar(20) NOT NULL CHECK(status IN ('CONFIRMED','REJECTED','CANCELLED','BACKORDERED')),reason varchar(255),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items (order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id bigint NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,product_id varchar(20) NOT NULL,quantity integer NOT NULL CHECK(quantity>0));
CREATE TABLE notifications (notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,message varchar(255) NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS supplier_orders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_id varchar(20) NOT NULL,buyer_ref varchar(100) NOT NULL UNIQUE,request_id varchar(100) NOT NULL,po_number varchar(50),cases integer NOT NULL,units integer NOT NULL,status varchar(30) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tiangge_state (id bigint PRIMARY KEY,cursor bigint NOT NULL);
CREATE TABLE tiangge_processed_events (event_id varchar(100) PRIMARY KEY,seq bigint NOT NULL,processed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tiangge_pending_stock (seller_sku varchar(40) PRIMARY KEY,available integer NOT NULL CHECK(available>=0));
CREATE TABLE tiangge_order_links (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tiangge_order_id varchar(100) NOT NULL UNIQUE,shop_order_id bigint NOT NULL REFERENCES orders(order_id),decision varchar(30) NOT NULL,restocked boolean NOT NULL DEFAULT false);
INSERT INTO inventory(product_id,name,stock) VALUES ('P100','Wireless Mouse',25),('P200','Mechanical Keyboard',10),('P300','USB-C Hub',0);
INSERT INTO tiangge_state(id,cursor) VALUES (1,0);
