-- System Integration: Modular Monolith
-- Run this script in the Supabase SQL Editor.

create table if not exists inventory (
    product_id varchar(20) primary key,
    name varchar(100) not null,
    stock integer not null check (stock >= 0)
);

create table if not exists orders (
    order_id bigint generated by default as identity primary key,
    product_id varchar(20) not null,
    quantity integer not null check (quantity > 0),
    status varchar(20) not null check (status in ('CONFIRMED', 'REJECTED')),
    reason varchar(255),
    created_at timestamptz not null default now()
);

insert into inventory (product_id, name, stock)
values
    ('P100', 'Wireless Mouse', 25),
    ('P200', 'Mechanical Keyboard', 10),
    ('P300', 'USB-C Hub', 0)
on conflict (product_id)
do update set
    name = excluded.name,
    stock = excluded.stock;
